python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.1 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.2 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.3 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.4 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.5 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.6 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.7 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.8 --epochs=30
python ../code/main.py --eval=KAR --target=mnist --attention=CAM --method=CAM --ratio=0.9 --epochs=30