python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.1
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.2
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.3
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.4
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.5
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.6
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.7
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.8
python ../code/main.py --eval=ROAR --target=cifar10 --attention=CBAM --method=GC --ratio=0.9